//页面链接定义
export default {
    //展示模块
    home: '',
    cooperation: '/cooperation',
    tutorial: '/tutorial',
    model: '/model',
    social: '/3dexhibition',
    guide: '/guide',
    pay: '/pay',
    payIntroduce: '/pay/introduce',
    modelPreview: '/model/preview',
    service: '/service',
    globalSearch: '/search',
    gallery: '/gallery',
    artworkPublic: '/artwork',
    artworkPublicOption: '/option/artwork',
    copyright: '/copyright',
    notFound: '/not/found',
    login: '/login',
    homePagePreview: '/homePage/preview',
    cart: '/cart',


    user: '/',
    editor: '/editor/',

    //电商模块
    orderConfirm: '/order/confirm',
    orderDetail: '/order/detail/',
    orderSaleDetail: '/order/sale/detail/',
    orderPay: '/order/pay/',
    orderResult: '/order/result/',
    myOrder: '/dashboard/order',
    tradeManagement: '/dashboard/trade',
    goodsManage: '/dashboard/goods',
    walletManage: '/dashboard/wallet',
    appDownload: '/dashboard/app',

    //后台模块
    personal: '/dashboard',
    dashboardApp: '/dashboard/app',
    artwork: '/dashboard/artwork',
    artworkDetail: '/artwork/',
    artist: '/dashboard/artist',
    address: '/dashboard/address',
    mobileSetting: '/dashboard/m/setting',
    sculpture: '/dashboard/sculpture',
    sculptureDetail: '/sculpture/',
    exhibitionManage: '/dashboard/3dexhibition',
    statistics: '/dashboard/analytics',
    versionManage: '/dashboard/copyright',
    setting: '/dashboard/setting',
    account: '/dashboard/account',
    search: '/dashboard/search',
    description: '/dashboard/description',
    contection: '/dashboard/contection',
    activity: '/dashboard/activity',
    homeArtworkDetail: '/openwork/',
    homepage: '/3D/',

    exhibitionDetail: '/exhibition/',
}